# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
osx_image: xcode8.2
language: objective-c

env:
  - DESTINATION="platform=OS X"
  - DESTINATION="platform=iOS Simulator,name=iPhone SE"
  - DESTINATION="platform=tvOS Simulator,name=Apple TV 1080p"
  - DESTINATION=""

before_install:
  - xcrun simctl delete DB794781-65A7-4884-8D00-AAC3CBD39A44 # workaround for https://github.com/travis-ci/travis-ci/issues/7031

script:
  - if [[ $DESTINATION = "" ]]; then swift test; else set -o pipefail && xcodebuild -scheme CopyOnWrite -destination "$DESTINATION" test analyze | xcpretty -c; fi
  - pod lib lint --quick

after_success:
  - bash <(curl -s https://codecov.io/bash)
